import React, { useState } from 'react';
import { CloudRain, Globe, Share2, Radio, X, Shield, FileText, AlertCircle, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';

export const Footer = () => {
  const [activeModal, setActiveModal] = useState(null);

  const legalContent = {
    privacy: {
      title: "Privacy Policy",
      icon: Shield,
      updated: "August 2026",
      content: [
        "At Weather Index, we take your privacy seriously. This policy outlines how we collect, process, and protect your atmospheric and location query data.",
        "1. Information Collection: We gather localized query parameters (block, village, district coordinates) and non-personally identifiable telemetry to execute rainfall prediction models.",
        "2. Data Utilization: Your query inputs are processed through our AI inference models strictly to generate localized rainfall departure and monsoon break risk assessments.",
        "3. Data Sharing: We do not sell or monetize location queries. Aggregated regional statistics may be shared with government agricultural research authorities (MoES/IMD) for public safety advisories.",
        "4. Security: All network traffic and session inputs are encrypted using TLS 1.3 standards and secure cloud infrastructure."
      ]
    },
    terms: {
      title: "Terms of Use",
      icon: FileText,
      updated: "August 2026",
      content: [
        "Welcome to Weather Index. By accessing or using our climate intelligence platform, you agree to comply with these terms.",
        "1. Advisory Scope: Weather Index provides probabilistic monsoon rainfall predictions, climate signal analysis, and crop management advisories based on machine learning models.",
        "2. User Responsibilities: Agricultural officers, farmers, and researchers should use this information as a decision-support tool in conjunction with official IMD notifications.",
        "3. Platform Integrity: Users are prohibited from reverse engineering our API endpoints, automated scraping of predictive models, or attempting unauthorized system access.",
        "4. Modifications: We reserve the right to refine model parameters, features, and system architecture as new climate training datasets become available."
      ]
    },
    disclaimer: {
      title: "Disclaimer",
      icon: AlertCircle,
      updated: "August 2026",
      content: [
        "Important Operational Disclaimer:",
        "Weather Index processes global climate signals (such as Indian Ocean Dipole, ENSO, and MJO) using statistical and deep learning regression models to generate predictive forecasts.",
        "1. Probabilistic Nature: Meteorological forecasting is inherently probabilistic. Predictions generated by this platform represent statistical probabilities rather than guaranteed future outcomes.",
        "2. Informational Purpose: All output data, risk categories, anomaly metrics, and agricultural advisories are provided strictly for informational and advisory planning purposes.",
        "3. Liability Limitation: Neither Weather Index nor its development contributors assume liability for agricultural losses, crop yield variations, or financial decisions made based on probabilistic predictions."
      ]
    }
  };

  return (
    <footer className="w-full bg-[#04060E] text-slate-400 border-t border-slate-900 transition-colors relative">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12 py-16">
        <div className="grid grid-cols-1 md:grid-cols-6 gap-10">
          
          {/* Brand Column (2 Spans) */}
          <div className="md:col-span-2 space-y-4">
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-sky-500 to-blue-600 flex items-center justify-center text-white shadow-md">
                <CloudRain className="w-5 h-5 text-white" />
              </div>
              <span className="font-extrabold text-xl text-white font-sans tracking-tight">
                VARSHA <span className="text-sky-400">SETU</span>
              </span>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed max-w-sm">
              Climate Intelligence for smarter decisions. Understand the monsoon, prepare before it changes.
            </p>
          </div>

          {/* Column 2: Platform */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-200">Platform</h4>
            <ul className="space-y-2 text-xs">
              <li><a href="#capabilities" className="hover:text-sky-400 transition-colors">Features</a></li>
              <li><a href="#how-it-works" className="hover:text-sky-400 transition-colors">How It Works</a></li>
              <li><Link to="/login" className="hover:text-sky-400 transition-colors">Platform Login</Link></li>
              <li><Link to="/dashboard" className="hover:text-sky-400 transition-colors">Get Started</Link></li>
            </ul>
          </div>

          {/* Column 3: Resources */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-200">Resources</h4>
            <ul className="space-y-2 text-xs">
              <li><a href="#capabilities" className="hover:text-sky-400 transition-colors">Climate Signals</a></li>
              <li><a href="#how-it-works" className="hover:text-sky-400 transition-colors">AI Models</a></li>
              <li><a href="#capabilities" className="hover:text-sky-400 transition-colors">Crop Advisory</a></li>
            </ul>
          </div>

          {/* Column 4: Legal (Functional Links) */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-200">Legal</h4>
            <ul className="space-y-2 text-xs">
              <li>
                <button onClick={() => setActiveModal('privacy')} className="hover:text-sky-400 transition-colors text-left">
                  Privacy Policy
                </button>
              </li>
              <li>
                <button onClick={() => setActiveModal('terms')} className="hover:text-sky-400 transition-colors text-left">
                  Terms of Use
                </button>
              </li>
              <li>
                <button onClick={() => setActiveModal('disclaimer')} className="hover:text-sky-400 transition-colors text-left">
                  Disclaimer
                </button>
              </li>
            </ul>
          </div>

          {/* Column 5: Connect */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-200">Connect</h4>
            <div className="flex items-center space-x-3">
              <a href="#" className="p-2 rounded-full bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-slate-700 transition-colors">
                <Globe className="w-4 h-4" />
              </a>
              <a href="#" className="p-2 rounded-full bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-slate-700 transition-colors">
                <Share2 className="w-4 h-4" />
              </a>
              <a href="#" className="p-2 rounded-full bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-slate-700 transition-colors">
                <Radio className="w-4 h-4" />
              </a>
            </div>
          </div>

        </div>

        {/* Footer Bottom Bar (SIH identifier removed) */}
        <div className="mt-14 pt-8 border-t border-slate-900 flex flex-col md:flex-row items-center justify-between text-xs text-slate-500">
          <p>© 2026 VarshaSetu. All rights reserved.</p>
        </div>
      </div>

      {/* ============================================================ */}
      {/* FUNCTIONAL LEGAL MODAL WINDOW */}
      {/* ============================================================ */}
      <AnimatePresence>
        {activeModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
              className="w-full max-w-2xl bg-[#0A0F1D] border border-sky-500/40 rounded-3xl p-6 sm:p-8 shadow-[0_0_50px_rgba(6,182,212,0.3)] space-y-6 relative text-left"
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between border-b border-slate-800/80 pb-4">
                <div className="flex items-center space-x-3">
                  <div className="p-2.5 rounded-2xl bg-sky-500/10 border border-sky-500/30 text-sky-400">
                    {React.createElement(legalContent[activeModal].icon, { className: "w-5 h-5" })}
                  </div>
                  <div>
                    <h3 className="text-lg font-black text-white">{legalContent[activeModal].title}</h3>
                    <p className="text-[10px] text-slate-400 font-mono">Effective: {legalContent[activeModal].updated}</p>
                  </div>
                </div>
                <button
                  onClick={() => setActiveModal(null)}
                  className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-400 hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Modal Content */}
              <div className="space-y-4 max-h-[60vh] overflow-y-auto pr-2 text-xs text-slate-300 leading-relaxed font-sans">
                {legalContent[activeModal].content.map((paragraph, pIdx) => (
                  <p key={pIdx} className="bg-slate-900/40 p-3 rounded-xl border border-slate-800/60">
                    {paragraph}
                  </p>
                ))}
              </div>

              {/* Modal Action Footer */}
              <div className="pt-4 border-t border-slate-800/80 flex justify-end">
                <button
                  onClick={() => setActiveModal(null)}
                  className="px-6 py-2.5 rounded-full bg-gradient-to-r from-blue-600 to-sky-500 text-white font-bold text-xs shadow-md hover:scale-105 transition-all flex items-center space-x-2"
                >
                  <ArrowLeft className="w-3.5 h-3.5" />
                  <span>Return to Weather Index</span>
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </footer>
  );
};
