import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function downloadPdfReport(elementId, districtName = 'District', cropName = 'Crop') {
  const element = document.getElementById(elementId);
  
  if (element) {
    try {
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#0A0F1D',
        logging: false
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      const cleanDistrict = districtName.replace(/\s+/g, '_');
      const cleanCrop = cropName.replace(/\s+/g, '_');
      pdf.save(`VarshaSetu_Report_${cleanDistrict}_${cleanCrop}.pdf`);
      return;
    } catch (err) {
      console.warn('Canvas PDF capture failed, using formatted vector PDF fallback:', err);
    }
  }

  // Direct vector jsPDF fallback
  const pdf = new jsPDF();
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(20);
  pdf.text('VARSHA SETU - CLIMATE INTELLIGENCE REPORT', 14, 22);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.text(`Target District: ${districtName}`, 14, 34);
  pdf.text(`Target Crop: ${cropName}`, 14, 42);
  pdf.text(`Generated Date: ${new Date().toLocaleString('en-IN')}`, 14, 50);

  pdf.setLineWidth(0.5);
  pdf.line(14, 55, 196, 55);

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(13);
  pdf.text('Executive Summary & Advisory', 14, 66);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text('This official report provides localized climate forecasts, monsoon rainfall deviation,', 14, 76);
  pdf.text('and FAO-56 Crop Water Balance metrics generated by VarshaSetu.', 14, 82);

  pdf.save(`VarshaSetu_Report_${districtName.replace(/\s+/g, '_')}.pdf`);
}

export function generateClimateReport(location = {}, crop = {}, predictionData = null) {
  const districtName = location.district || location.name || 'Bengaluru Rural';
  const cropName = crop.name || crop.key || 'Ragi';
  downloadPdfReport(null, districtName, cropName);
}
